### ISSUE TITLE
Unable to login after creating a user and logging out

### ISSUE THREAD

**Issue by mcorkum** [envault/envault#38]
I am able to install as per the guide. 

However, once I logout and try to log in again I get a 500 error. Is there something I missed in setup?

**Comment by danharrin** [comment]
Hey @mcorkum, can you check the Laravel log  / enable debug mode in your `.env` so we can see the exact error that has occurred?

**Comment by mcorkum** [comment]
Hey @danharrin thanks for replying - I just found my mistake. My mail was misconfigured I think.

**Comment by danharrin** [comment]
Awesome, no worries!
