### ISSUE TITLE
No .env found with env

### ISSUE THREAD

**Issue by jmurphy45** [envault/envault#39]
**Describe the bug**
When pasting the initialization command into the terminal of my project that has a env file currently. I get an error that says it does not exist.
`Welcome to Envault! No more .env update nightmares from now on, we promise 🤗
Connecting to your Envault server... done
A .env file was not found. Would you like to create a new one? Y/n: 
`
When putting y in the prompt it follows with:
` TypeError: Cannot read property 'writeFile' of undefined`

**To reproduce**
1.  Open preexisting project with env file
2. Copy in supplied command from interface
2. Run command 

**Expected behavior**
Should setup the environment for Envault.

**Context**
- Browser: Chrome
- PHP version: 7.4

**Additional details**
Seems like a js bug but no place to put issues for the cli.

**Comment by danharrin** [comment]
Hey, I can't reproduce this issue... could you please check it's still present on the latest version? Thanks.
