### ISSUE TITLE
Incorrect Field Definition in Failed Job Table 

### ISSUE THREAD

**Issue by iantasker** [envault/envault#41]
**Describe the bug**

The `CreateFailedJobsTable` migration defines id field when a uuid field is required.

**To reproduce**
Steps to reproduce the behaviour:
1. Get the latest version of the repo
2. Set invalid email stmp settings (so a job will fail)
3. Run `php artisan migrate`
4. Try and login
5. Review logs 

**Expected behaviour**
The migration should have the field name and type. 

**Context**
- PHP version: [e.g. 7.4] 7.4.15
- Laravel Version: 8.12

**Additional details**
Add any other details about the problem here.

**Comment by danharrin** [comment]
Hey, this should be fixed in the latest version 👍
