### ISSUE TITLE
no found livewire.js

### ISSUE THREAD

**Issue by DevMakoto** [envault/envault#50]
**Describe the bug**
does not complete registration in setup step

**To reproduce**
1. Install Clean

**Expected behavior**
visually it didn't show me an error, but when checking the console it couldn't find the livewire.js file

**Screenshots**
![image](https://user-images.githubusercontent.com/4119035/122506776-98430200-cfc4-11eb-9ed6-7a1dde8d0894.png)

**Additional details**
run `php artisan livewire:publish` and solved, pls add in readme

**Comment by danharrin** [comment]
Hi, this is not a recommended installation step since Livewire should be automatically discovered. Since this is an issue with Livewire conflicting with your hosting environment, I will close this issue.
