### ISSUE TITLE
No change detected, I have many change

### ISSUE THREAD

**Issue by SebastienOuellet** [envault/envault#52]
Hi,

i am having an issue where it is telling me that i ma up to date but I have many change that would need to be updated

....\nessaApp>npx envault --force
Welcome to Envault! No more .env update nightmares from now on, we promise �
Connecting to your Envault server... done
You are already up to date �

As you can see on the printscreen it should update the 6 others variable i have setup
![image](https://user-images.githubusercontent.com/7582954/125378780-57d56a80-e35d-11eb-8546-3d8cd7d2af64.png)

To be able to refresh, i have to delete the .env then run the cmd npx envault and it will work,.. Not a big deal to delete the env each time but think I should let you know. 

Thanks again, 

*sorry for the poor english*

**Comment by danharrin** [comment]
Hey, I can't replicate this issue at all, so I'm going to close it until someone else can and can give replication instructions. Thanks for your report.
