### ISSUE TITLE
All requests are done using HTTPS

### ISSUE THREAD

**Issue by amandiobm** [envault/envault#64]
Hey all,

I just installed this locally to give it a go, I've used [Docker](https://github.com/envault/envault/discussions/1), and was awesome.

I was able to add users, apps, and variables. but I could not update my local projects.

`npx envault dev-envault.local 1 A0SFe6y3yJtV3oKH`
---
`Error: Looks like your setup token is invalid, please get another!`.

This is due to the Axios is forcing `HTTPS`?! There is a way to overcome this?!

Could the command grab the entire `APP_URL` defined on `.env`
`npx envault http://dev-envault.local 1 A0SFe6y3yJtV3oKH`

I could create a PR to this is a good approach

Best regards,

**Comment by danharrin** [comment]
Hey, yes HTTPS is forced. Otherwise, your environment variables would be transported unencrypted across the network. We're not taking responsibility for security vulnerabilities because of that.

**Comment by amandiobm** [comment]
Hey, tks for replying.

I get the reason why it should be HTTPS, although, for testing locally, I don't have an SSL certificate. And the responsibility of using HTTP or HTTPS should be from the user, not the app.

As I mentioned we can use the whole `APP_URL`, we can display a warning message if `APP_URL` protocol is not HTTPS, which makes it more open to others usage not only production environment.

And on envault CLI, we remove the `HTTPS`, since $server will have the whole URL.

Best regards.

**Comment by danharrin** [comment]
If you'd like to make a PR to the CLI to fix this, you're more than welcome.

**Comment by amandiobm** [comment]
Awesome! Will do.

Best regards

**Comment by amandiobm** [comment]
Hey @danharrin

Just created the PR on the CLI and Envault, take a look and let me know if any changes are necessary.

regards
